### ISSUE TITLE
Support newer versions of scipy

### ISSUE THREAD

**Issue by sorenwacker** [griquelme/tidyms#3]
As a feature request, I would like to use the tool with a more recent version of `scipy`. At least 1.6.2.

**Comment by griquelme** [comment]
Hi,  I included this requirement in the scipy version because there have been changes in how the ridge lines were identified in the scipy find_peaks_cwt function that created some problems in the detection of overlapping peaks. I am currently working on improving peak detection in those cases. Once this is done, the library will compatible with the last version of scipy.

**Comment by sbolushevsky** [comment]
Hi,
Is it possible to put in a new parameter like 'plateau_size' in the find_peaks() as well?
I have a peak that can no be found with tidyms.Chromatogram.find_peaks() function.
Thank you

**Comment by griquelme** [comment]
Hi @sbolushevsky, do you mean a `plateau_size` like the one used in the  `find_peaks` function from scipy?

https://docs.scipy.org/doc/scipy/reference/generated/scipy.signal.find_peaks.html

I am currently working on improving the `find_peaks` function and hopefully in the following weeks I will include this new version in the PyPI repository. Would you be able to provide me the chromatogram with the problematic peaks?

**Comment by sbolushevsky** [comment]
Sounds good!

I finally managed to find a workaround for this and get this peak found. I noticed that there are two points with the same y_max value (1980). I have deleted the duplicate from the data and reran the function.

Please find jupyter notebook file and mzML for this peak (id=5)

[210607-fu_b-5.mzML.txt](https://github.com/griquelme/tidyms/files/6633900/210607-fu_b-5.mzML.txt)
[flat peak - git.ipynb.txt](https://github.com/griquelme/tidyms/files/6633894/flat.peak.-.git.ipynb.txt)

**Comment by griquelme** [comment]
Thanks! I'll get back to you when I finish testing the new implementation of the function.
